### ISSUE TITLE
Great work!

### ISSUE THREAD

**Issue by mgcrea** [BJORNDEBEN/Fabtotum-Head-cable#1]
Hey Bjorn!

I broke the ribbon cable of my original Fabtotum printer yesterday and was a bit desperate to find a solution to fix it. Finally end up finding the facebook group and your awesome work. Thanks for giving me hope!

However when looking at the PCB pictures, I'm wondering how do you connect the orginal motor driver board to [your "replacement" PCB](https://www.pcbgogo.com/feedback/Replacement_pcb_for_fabtotum_3d_printer.html)? Does it require a generic small flex pcb cable? Where did you buy it?

Also how do you mount your [head PCB](https://www.pcbgogo.com/feedback/Pcb_for_wired_printing_head_fabtotum.html) do you have pictures of final assembly?

Does your solution currently works or is it still a WIP?

Thanks a lot!

**Comment by BJORNDEBEN** [comment]
There are 2 types of cable. The old version is a 50 pin cable. The new one is a 20 pin cable. Mi replacement is for the new cable. there is a PCB on both side's of my cable. First let me know which cable you have.

**Comment by BJORNDEBEN** [comment]
just updated everything. pictures and a video are added

**Comment by mgcrea** [comment]
It looks like I have the V1 cable:

![D2D510C3-FF73-43A8-B0DE-8CECB8CB4BDB_1_105_c](https://user-images.githubusercontent.com/108273/82647456-856dca80-9c16-11ea-941e-464fcd3618ca.jpeg)

Is there any way to upgrade from the V1 to V2? Does it require to upgrade the motor driver board (FABlin)?

Thanks again!

**Comment by BJORNDEBEN** [comment]
you are lucky to have the V1. you can buy one from Ryan Zweifel in the facebook group.

https://www.facebook.com/groups/1052715011528991/permalink/1895629217237562/

**Comment by mgcrea** [comment]
Found someone in Europe with a spare! But I'm now considering replacing the existing driving board altogether thanks to your PCB, see #2.
